variables:
  UBUNTU_VERSION: "22.04"
  QUARTO_VERSION: "1.3.361"
  R_VERSION: "4.3.3" # You can modify this to the desired R version

image:
  name: r-base:${R_VERSION}
  entrypoint: ["bash", "-c"]

before_script:
  - apt-get update && apt-get install -y curl
  - apt-get install -y xorg-dev libgstreamer-plugins-base0.10-dev libgstreamer0.10-dev libjpeg-dev libusb-1.0-0-dev
  - curl -L -o quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
  - dpkg -i quarto.deb && rm -f quarto.deb
  - quarto install --no-prompt extension quarto-ext/lightbox
  - Rscript -e "install.packages(c('rmarkdown', 'jsonlite', 'readODS', 'wordcloud'), dependencies = TRUE)" # Add R packages here

pages:
  script:
    - quarto render . --to html --output-dir=public/
  artifacts:
    paths:
      - public/
  only:
    - main