variables:
  UBUNTU_VERSION: "22.04"
  QUARTO_VERSION: "1.3.361"
  R_VERSION: "4.2.2"

image:
  name: "rocker/verse:latest"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -L -o quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
  - dpkg -i quarto.deb && rm -f quarto.deb
  - quarto install --no-prompt extension quarto-ext/lightbox
  - Rscript -e "install.packages(c('rmarkdown', 'rjson', 'jsonlite', 'readODS', 'DT', 'wordcloud', 'stringi', 'crosstalk'), dependencies = TRUE)"

pages:
  script:
    - quarto render . --to html --output-dir=public/
  artifacts:
    paths:
      - public/
  only:
    - main
