project:
  type: book
  output-dir: public

execute: 
  echo: false
  warning: false

book:
  title: "NFDI4Objects Research Data Management Competency Framework"
  author: # vgl. https://quarto.org/docs/journals/authors.html
  - name: Jane Roe
    orcid: 0000-0000-0000-0000
    email: email@example.org
    affiliation: 
      - name: Incredible Campus
        city: Outer State
        url: https://example.org
    attributes:
      corresponding: true
      equal-contributor: true
  - name: John Doe
    orcid: 0000-0000-0000-0000
    email: email@example.org
    affiliation: 
      - name: Party University
        city: Moon
        url: https://example.org
    attributes:
      corresponding: false
      equal-contributor: true
  date: today
  date-format: DD MMMM, YYYY
  page-navigation: true
  site-url: https://gitlab.rlp.net/n4o/competence_framework/
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Current state"
      chapters:
      - current-state-overview.qmd
      - catalogue.qmd
      - analysis.qmd
    - part: "NFDI4Objects Competency framework"
      chapters:
        - framework.qmd
        - area-1.qmd
        - area-2.qmd
        - area-3.qmd
        - area-4.qmd
        - attitudes.qmd
    - recommendations.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
    fig-format: svg
    css: styles.css
  pdf:
    documentclass: scrreprt



